export const types = {
  SYNC_TITLE: 'TODO_EXAMPLE/SYNC_TITLE',
  ADD_TODO: 'TODO_EXAMPLE/ADD_TODO',
  TOGGLE_COMPLETED: 'TODO_EXAMPLE/TOGGLE_COMPLETED',
  REMOVE_COMPLETED_TODOS: 'TODO_EXAMPLE/REMOVE_COMPLETED_TODOS',
} as const;
